language: python
python:
  - "3.6"
  - "2.7"
# command to install dependencies
install:
  - pip install Cython --install-option="--no-cython-compile"
  - pip install numpy
# command to run tests
script: python test_everything.py