language: python
python:
  - "3.6"
  - "2.7.12"
# command to install dependencies
install: 
  - pip install Cython --install-option="--no-cython-compile"
  - pip install numpy
  - pip install matplotlib
  - python setup.py install
# command to run tests
script: python test_everything.py test_as_site-package