language: python
python:
  - "3.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --install-option='--no-cython-compile'"
# command to run tests
script: python test_everything.py