
version: 4.0a17.{build}

image: Visual Studio 2019

environment:
  PYPIPA:
    secure: OYHmXK1t/zHOfA97P+RmCVDWG1ef8lyMQaNK/jmVAXk=
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

install:
#  - cinst nsis
  - ps: (new-object net.webclient).DownloadFile('https://downloads.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe', 'nsis-3.05-setup.exe')
  - ps: nsis-3.05-setup.exe /S
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - python -m pip install cython
  - python -m pip install numpy
  - python -m pip install scipy
  - python -m pip install matplotlib
  - python -m pip install bokeh
  - python -m pip install black
  - python -m pip install netcdf4
  - python -m pip install networkx
  - python -m pip install pandas
  - python -m pip install plotly
  - python -m pip install pynsist
  - python -m pip install setuptools
  - python -m pip install typing_extensions
  - python -m pip install twine
  - python -m pip install wheel
  - python -m pip install wrapt
  - python -m pip install xmlschema

build: off

before_test:
  - python disable_autodoc.py
  - python setup.py install
  - python make_and_install_dists.py
  - python -m pip install attrs
  - python prepare_hydpy_installer.py
  - pynsist make_hydpy_installer.cfg
  - python -m pip uninstall cython --yes
  - rename hydpy _hydpy

test_script:
  - hyd.py test_everything
  - cd dist
  - python -m pip uninstall hydpy --yes
  - cd..
  - python call_installer.py
  - SET PATH=C:\Users\appveyor\AppData\Local\Programs\HydPy\bin;%PATH%
  - hyd.py test_everything

after_test:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: tyralla >> %USERPROFILE%\\.pypirc"
  - "echo password: %PYPIPA% >> %USERPROFILE%\\.pypirc"
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Invoke-Expression "twine upload --skip-existing dist/*"} else { write-output "No tag, no deploy"}
    
artifacts:
  - name: Packages
    path: dist\*
  - name: Installer
    path: build\nsis\HydPy*.exe
  - name: XSDs
    path: _hydpy\conf\*.xsd

deploy:
  description: 'This is a draft.'
  provider: GitHub
  auth_token:
    secure: n6oPRXEu1EFeFsmJYY2qnyuEOsb6OuSXQ5kf6CacHvcFcKb6JWXqPYZBzk16ZCBn
  artifact: Packages,Installer,XSDs
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
