
version: 3.2a6.{build}

environment:
  PYPIPA:
    secure: OYHmXK1t/zHOfA97P+RmCVDWG1ef8lyMQaNK/jmVAXk=
  matrix:
    - PYTHON: C:\\Miniconda3-x64\\envs\\myenv
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
    - PYTHON: C:\\Miniconda3-x64\\envs\\myenv
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

install:
  - SET PATH=C:\\Miniconda3-x64;C:\\Miniconda3-x64\\Scripts;%PATH%
  - conda create -n myenv python=%PYTHON_VERSION% --yes
  - activate myenv
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install cython
  - conda install numpy --yes
  - conda install scipy --yes
  - conda install matplotlib --yes
  - python -m pip install bokeh
  - python -m pip install pandas
  - python -m pip install setuptools
  - python -m pip install twine
  - python -m pip install wheel
  - python -m pip install wrapt
  - python -m pip install xmlschema
  - conda install netcdf4 --yes
  - conda uninstall netcdf4 --yes
  - python -m pip install netcdf4

build: off

before_test:
  - python disable_autodoc.py
  - python setup.py install
  - python make_and_install_dists.py
  - pip uninstall cython --yes

test_script:
  - python hydpy/tests/test_everything.py forcecompiling=False

artifacts:
  - path: dist\*
  - path: hydpy\conf\HydPyConfigBase.xsd

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: tyralla >> %USERPROFILE%\\.pypirc"
  - "echo password: %PYPIPA% >> %USERPROFILE%\\.pypirc"
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Invoke-Expression "twine upload --skip-existing dist/*"} else { write-output "No tag, no deploy"}
